### ISSUE TITLE
Line108 in pfam_scan.py if (n := len(db_paths)) > 1:

### ISSUE THREAD

**Issue by Dabaixian** [aziele/pfam_scan#1]
Hi Aziele,
     when using your code, there is something wrong with pfam_scan.py in line108. I wonder what is the meaning of the n, and where shall we define it? Besides, i can't understander the :=. Sorry for borthering you, could you please help me with these? Thank you very much!

**Comment by aziele** [comment]
Hi Debaixian,
I appreciate your interest in pfam_scan.py. I'm guessing you are using an earlier version of python than 3.8. Starting from Python 3.8, `:=` is an operator that allows assigning variables within expressions (e.g., within the condition in an if statement). To fix the issue, you can either install Python >= 3.8, or you can replace line 108 with the following two lines:

```
n = len(db_paths)
if n > 1:
```

**Comment by Dabaixian** [comment]
Hi Aziele,
    How kind of you，Thank you for your patient and meticulous answer! Now i can keep trying the code after your help：）
    All the best to you：）

**Comment by aziele** [comment]
Sure! Feel free to let me know if you need more help.

**Comment by Dabaixian** [comment]
Aziele，You are so considerate，Thank you very very much！
